# Generated by Django 3.2.4 on 2021-06-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversational', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversations',
            new_name='Conversation',
        ),
    ]
