# Generated by Django 3.2.4 on 2021-06-10 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conversational', '0006_conversation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 20, 25, 26, 928631, tzinfo=utc)),
        ),
    ]
