# Generated by Django 3.2.4 on 2021-06-10 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversational', '0010_alter_conversation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
